name: CI

on:
    push:
        branches:
            - master
            - "**"
    pull_request:
        branches:
            - master

jobs:
    lint:
        name: Ruff lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
                uses: actions/setup-python@v4
                with:
                    python-version: 3.11
            - name: Install ruff
                run: |
                    python -m pip install --upgrade pip
                    pip install ruff
            - name: Run ruff
                run: |
                    ruff check .

    type-check:
        name: Mypy type-check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
                uses: actions/setup-python@v4
                with:
                    python-version: 3.11
            - name: Install mypy
                run: |
                    python -m pip install --upgrade pip
                    pip install mypy
            - name: Run mypy
                run: |
                    mypy --ignore-missing-imports app tests

    test:
        name: Tests
        runs-on: ubuntu-latest
        needs: [lint, type-check]
        strategy:
            matrix:
                python-version: [3.11]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
                uses: actions/setup-python@v4
                with:
                    python-version: ${{ matrix.python-version }}
            - name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
                    if [ -f pyproject.toml ]; then pip install -e . ; fi
            - name: Run tests
                run: |
                    pytest -q
